package com.procurement.procurement.service.report;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.procurement.procurement.dto.report.ReportRequestDTO;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

@Service
public class ReportService {

    public byte[] generateVendorReport(ReportRequestDTO request, String format) {
        try {
            if ("excel".equalsIgnoreCase(format)) {
                return generateExcel(request);
            }
            return generatePdf(request);
        } catch (Exception e) {
            e.printStackTrace();
            throw new RuntimeException("Report generation failed: " + e.getMessage(), e);
        }
    }

    // ===================== PDF =====================
    private byte[] generatePdf(ReportRequestDTO request) throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, out);
        document.open();

        // ── Title ──
        com.itextpdf.text.Font titleFont = new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 20,
                com.itextpdf.text.Font.BOLD, BaseColor.DARK_GRAY);
        Paragraph title = new Paragraph("Vendor Procurement Report", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(20);
        document.add(title);

        // ── Filter Info ──
        com.itextpdf.text.Font infoFont = new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 11);
        if (request.getVendorId() != null) {
            document.add(new Paragraph("Vendor ID   : " + request.getVendorId(), infoFont));
        }
        if (request.getStartDate() != null) {
            document.add(new Paragraph("From        : " + request.getStartDate(), infoFont));
        }
        if (request.getEndDate() != null) {
            document.add(new Paragraph("To          : " + request.getEndDate(), infoFont));
        }
        document.add(Chunk.NEWLINE);

        // ── Table ──
        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{1f, 3f, 2f, 2f});
        table.setSpacingBefore(10);

        // header row
        addTableHeader(table, "ID");
        addTableHeader(table, "Vendor Name");
        addTableHeader(table, "Rating");
        addTableHeader(table, "Status");

        // sample data rows — replace with real DB data later
        addTableRow(table, "1", "ABC Traders", "4.5", "ACTIVE");
        addTableRow(table, "2", "XYZ Supplies", "4.2", "ACTIVE");
        addTableRow(table, "3", "Global Tech", "3.8", "INACTIVE");

        document.add(table);

        // ── Footer ──
        document.add(Chunk.NEWLINE);
        com.itextpdf.text.Font footerFont = new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 9,
                com.itextpdf.text.Font.ITALIC, BaseColor.GRAY);
        Paragraph footer = new Paragraph("Generated by Smart Procurement System", footerFont);
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);

        document.close();
        return out.toByteArray();
    }

    private void addTableHeader(PdfPTable table, String text) {
        com.itextpdf.text.Font headerFont = new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 11,
                com.itextpdf.text.Font.BOLD, BaseColor.WHITE);
        PdfPCell cell = new PdfPCell(new Phrase(text, headerFont));
        cell.setBackgroundColor(new BaseColor(63, 81, 181));
        cell.setPadding(8);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);
    }

    private void addTableRow(PdfPTable table, String... values) {
        com.itextpdf.text.Font rowFont = new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 10);
        for (String val : values) {
            PdfPCell cell = new PdfPCell(new Phrase(val, rowFont));
            cell.setPadding(6);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
        }
    }

    // ===================== Excel =====================
    private byte[] generateExcel(ReportRequestDTO request) throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Workbook workbook = new XSSFWorkbook();
        Sheet sheet = workbook.createSheet("Vendor Report");

        // header style
        CellStyle headerStyle = workbook.createCellStyle();
        Font headerFont = workbook.createFont();
        headerFont.setBold(true);
        headerStyle.setFont(headerFont);
        headerStyle.setFillForegroundColor(IndexedColors.ROYAL_BLUE.getIndex());
        headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

        // header row
        Row headerRow = sheet.createRow(0);
        String[] headers = {"ID", "Vendor Name", "Rating", "Status"};
        for (int i = 0; i < headers.length; i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(headerStyle);
            sheet.autoSizeColumn(i);
        }

        // data rows — replace with real DB data later
        Object[][] data = {
                {1, "ABC Traders", 4.5, "ACTIVE"},
                {2, "XYZ Supplies", 4.2, "ACTIVE"},
                {3, "Global Tech", 3.8, "INACTIVE"}
        };

        int rowNum = 1;
        for (Object[] rowData : data) {
            Row row = sheet.createRow(rowNum++);
            row.createCell(0).setCellValue((Integer) rowData[0]);
            row.createCell(1).setCellValue((String) rowData[1]);
            row.createCell(2).setCellValue((Double) rowData[2]);
            row.createCell(3).setCellValue((String) rowData[3]);
        }

        for (int i = 0; i < headers.length; i++) {
            sheet.autoSizeColumn(i);
        }

        workbook.write(out);
        workbook.close();
        return out.toByteArray();
    }
}
